Adding CSS Handles in orderOptions Component
vtex-apps/order-details pull request #13
Opened 2020-10-09 14:57 UTC by Caroladao

#### What does this PR do? \*
Adding CSS Handles in orderOptions Component

#### How to test it? \*
[Workspace](https://task238--menudigitalmx.myvtex.com/checkout/orderPlaced/?og=1067610540886)

![image](https://user-images.githubusercontent.com/38081030/95598569-756c5100-0a26-11eb-80d8-4fd17de225df.png)

2020-11-03 17:55 UTC, Caroladao commented
@klzns you can see this PR?

2020-11-03 22:31 UTC, klzns approved these changes

2020-11-04 15:47 UTC, kaisermann requested changes

2020-11-04 15:47 UTC, kaisermann commented on docs/README.md
> +| `cancelButton`   |
Can you order this alphabetically?

2020-11-04 15:47 UTC, kaisermann commented on react/OrderOptions.tsx
> +]
```suggestion
] as const
```

2020-11-04 16:38 UTC, Caroladao commented on docs/README.md
> +| `cancelButton`   |
yes

2020-11-11 12:44 UTC, Caroladao commented
@kaisermann it's right?

2020-11-25 12:48 UTC, Caroladao commented
@kaisermann I have already done the changes, could you validate please?

2024-08-26 17:46 UTC, closed without merging