Added CSS handles to payment method & address
vtex-apps/order-details pull request #23
Opened 2021-03-08 23:02 UTC by razvanudream

#### What does this PR do? \*

It simply adds some CSS handles on PaymentMethod and Address components in order to style those blocks

#### How to test it? \*

Link this updated version on workspace that has order-placed default implementation and inspect element to check for the new CSS handles

#### Related to / Depends on \*

![image](https://user-images.githubusercontent.com/71461884/110393321-00ec1b80-8073-11eb-8d6c-05e035205023.png)
![image](https://user-images.githubusercontent.com/71461884/110393350-106b6480-8073-11eb-9304-ce21a38f0001.png)

2021-03-09 12:52 UTC, igorbrasileiro commented on react/Address.tsx
> +  const handles = useCssHandles(CSS_HANDLES)
```suggestion
  const handles = useCssHandles(CSS_HANDLES)
  
```

2021-03-09 12:53 UTC, igorbrasileiro approved these changes
LGTM

2021-03-10 12:54 UTC, salesfelipe requested changes

2021-03-10 12:54 UTC, salesfelipe commented on react/tsconfig.json
> +    "jsx": "react",
```suggestion
```

2021-03-10 12:54 UTC, salesfelipe commented on react/PaymentMethod.tsx
> +        <p className={`${handles.paymentType} c-on-base`}>{paymentGroupSwitch(payment, intl)}</p>
```suggestion
        <p className={`${handles.paymentGroup} c-on-base`}>{paymentGroupSwitch(payment, intl)}</p>
```

2021-03-10 12:54 UTC, salesfelipe commented on react/PaymentMethod.tsx
> +  'paymentType',
```suggestion
  'paymentGroup',
```

2021-03-10 12:54 UTC, salesfelipe commented on CHANGELOG.md
> +- Added CSS Handles `paymentType` & `paymentValue` on PaymentMethod
```suggestion
- Added CSS Handles `paymentGroup` & `paymentValue` on PaymentMethod
```

2021-03-10 12:54 UTC, salesfelipe commented on docs/README.md
> +| `paymentType`   |
```suggestion
| `paymentGroup`   |
```

2021-03-10 17:06 UTC, salesfelipe approved these changes

2021-03-10 17:07 UTC, merged

2021-03-10 17:09 UTC, salesfelipe commented
Thanks for your contribution @razvanudream 🙏