Add CSS Handles to CostumerInfo's component
vtex-apps/order-details pull request #8
Opened 2020-05-05 14:14 UTC by LucasCastroAcctGlobal

#### What is the purpose of this pull request?

Add CSS Handles for the order-details component.

#### What problem is this solving?

Adds CSS classes so that you have greater flexibility in using items rendered by the order-details component.

### How should this be manually tested?
- Enter this link: https://orderplaced--tackoftheday.myvtex.com/checkout/orderPlaced/?og=1018171103781
- Inspect the element for the order-details component information;
- You will see that the new CSS Handles have been added.

### Screenshots or example usage
https://cl.ly/9022af914444

Types of changes
- [ ] - Bug fix (a non-breaking change which fixes an issue)
- [X] - New feature (a non-breaking change which adds functionality)
- [ ] - Breaking change (fix or feature that would cause existing functionality to change)
- [ ] - Requires change to documentation, which has been updated accordingly.

2020-05-07 19:07 UTC, klzns requested changes
Thanks for the PR! There's a typo in customer

2020-05-07 19:07 UTC, klzns commented on docs/README.md
> +| `costumerInfoListPhone`   |
```suggestion
| `customerInfoListContainer`   |
| `customerInfoListName`   |
| `customerInfoListEmail`   |
| `customerInfoListDocument`   |
| `customerInfoListPhone`   |
```

2020-05-07 19:07 UTC, klzns commented on react/CustomerInfo.tsx
> +]
```suggestion
] as const
```

2020-05-07 19:07 UTC, klzns commented on CHANGELOG.md
> +- CSS Handles for CostumerInfo component
```suggestion
- CSS Handles for CustomerInfo component
```

2020-05-11 13:50 UTC, klzns approved these changes

2020-05-11 13:55 UTC, salesfelipe approved these changes

2020-05-11 13:58 UTC, bivillar approved these changes

2020-05-11 14:04 UTC, merged

2020-05-11 14:12 UTC, klzns commented
@allcontributors add @LucasCastroAcctGlobal for code